# Generated by Django 2.2.26 on 2022-07-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220721_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessYearInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Business User')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Currency')),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_staff', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Staff')),
            ],
        ),
        migrations.CreateModel(
            name='PetsittingSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Software Company')),
            ],
        ),
        migrations.CreateModel(
            name='IntroduceYourself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_website', models.URLField()),
                ('hear_about_furgis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hear About Furgis')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CurrencyList')),
                ('how_long_in_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BusinessYearInterval')),
                ('number_of_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.NumberOfStaff')),
                ('pet_sitting_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PetsittingSoftware')),
            ],
        ),
    ]
