# Generated by Django 2.2.26 on 2022-09-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220920_1306'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='introduceyourself',
    #         name='company_website',
    #         field=models.URLField(),
    #     ),
    # ]
