# Generated by Django 2.2.26 on 2022-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220920_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('breed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Breed')),
                ('birth_date', models.DateField()),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('micro_chip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Micro Chip')),
                ('vaccination_current', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vaccinations Current')),
                ('sex', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sex')),
                ('neutered', models.CharField(blank=True, max_length=255, null=True, verbose_name='Neutered/Sprayed')),
                ('primary_vet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Vet')),
                ('alternate_vet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternate Vet')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
            ],
        ),
    ]
