# Generated by Django 2.2.26 on 2022-10-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Phone')),
                ('secondary_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Phone')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Role')),
            ],
        ),
    ]
