# Generated by Django 2.2.26 on 2022-10-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_role_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Staff')),
            ],
        ),
    ]
