# Generated by Django 2.2.26 on 2022-10-14 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20221014_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='assign_keys',
        ),
        migrations.AddField(
            model_name='keys',
            name='assign_keys',
            field=models.ManyToManyField(related_name='keysgenerated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keys',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
