# Generated by Django 2.2.26 on 2022-11-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20221014_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
