# Generated by Django 2.2.26 on 2022-11-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20221109_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
