# Generated by Django 2.2.26 on 2022-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_keys_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('name_client_visible', models.BooleanField(default=False)),
                ('name_client_editable', models.BooleanField(default=False)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship')),
                ('relationship_client_visible', models.BooleanField(default=False)),
                ('relationship_client_editable', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('email_client_visible', models.BooleanField(default=False)),
                ('email_client_editable', models.BooleanField(default=False)),
                ('primary_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Phone')),
                ('primary_phone_client_visible', models.BooleanField(default=False)),
                ('primary_phone_client_editable', models.BooleanField(default=False)),
                ('secondary_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Phone')),
                ('secondary_phone_client_visible', models.BooleanField(default=False)),
                ('secondary_phone_client_editable', models.BooleanField(default=False)),
                ('preffered', models.CharField(blank=True, max_length=255, null=True, verbose_name='Preffered & Do Not Schedule')),
                ('preffered_client_visible', models.BooleanField(default=False)),
                ('preffered_client_editable', models.BooleanField(default=False)),
                ('private_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Private Note')),
                ('private_note_client_visible', models.BooleanField(default=False)),
                ('private_note_client_editable', models.BooleanField(default=False)),
                ('client_added_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Added Date')),
                ('client_added_date_client_visible', models.BooleanField(default=False)),
                ('client_added_date_client_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SettingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_instruction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Instruction')),
                ('address_instruction_client_visible', models.BooleanField(default=False)),
                ('address_instruction_client_editable', models.BooleanField(default=False)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address One')),
                ('address1_client_visible', models.BooleanField(default=False)),
                ('address1_client_editable', models.BooleanField(default=False)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Two')),
                ('address2_client_visible', models.BooleanField(default=False)),
                ('address2_client_editable', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('city_client_visible', models.BooleanField(default=False)),
                ('city_client_editable', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('state_client_visible', models.BooleanField(default=False)),
                ('state_client_editable', models.BooleanField(default=False)),
                ('zip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip')),
                ('zip_client_visible', models.BooleanField(default=False)),
                ('zip_client_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SettingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254)),
                ('company_website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Website')),
                ('primary_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Phone Number')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondrary Phone Number')),
                ('address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address One')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Two')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='SettingPrimaryContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('cc_email', models.EmailField(max_length=254, verbose_name='CC Email')),
                ('primary_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Phone Number')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondrary Phone Number')),
                ('how_did_you_find_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='How Did You Find Us')),
            ],
        ),
    ]
