# Generated by Django 2.2.26 on 2022-11-16 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(auto_created=True, blank=True, default=None, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('due_date', models.DateField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('client', models.CharField(blank=True, default=None, max_length=50)),
                ('amount', models.CharField(blank=True, default=None, max_length=50)),
                ('balance', models.CharField(blank=True, default=None, max_length=50)),
                ('status', models.CharField(blank=True, default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('package_limit', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('package_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('taxable', models.BooleanField(default=False)),
                ('selectable_client', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('connected_service', models.TextField(null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('default_duration', models.IntegerField(null=True)),
                ('duration_unit', models.CharField(blank=True, default='Minutes', max_length=100)),
                ('mobile_app_timer', models.IntegerField(null=True)),
                ('mobile_app_timer_unit', models.CharField(blank=True, default='min', max_length=20)),
                ('selectable_by_client', models.BooleanField(default=False)),
                ('gps_route_tracking', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('late_reminder', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('description', models.TextField(null=True)),
                ('private_note', models.TextField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('taxable', models.BooleanField(default=False)),
                ('default_staff_rate', models.IntegerField(null=True)),
                ('default_staff_rate_unit', models.CharField(blank=True, default='%', max_length=25)),
                ('extra_pet_rate', models.IntegerField(null=True)),
                ('extra_pet_rate_unit', models.CharField(blank=True, default='pet', max_length=25)),
                ('staff_extra_pet_rate', models.IntegerField(null=True)),
                ('staff_extra_pet_rate_unit', models.CharField(blank=True, default='%', max_length=25)),
                ('service_group', models.CharField(blank=True, max_length=25, null=True)),
                ('service_scheduling', models.TextField(null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFrequencyPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_period', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=0)),
                ('when', models.IntegerField(null=True)),
                ('charge', models.IntegerField(null=True)),
                ('pay_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('pay_number', models.IntegerField(null=True)),
                ('pay_unit', models.CharField(blank=True, default='%', max_length=10)),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAutoFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_hours_enabled', models.BooleanField(default=False)),
                ('work_hours', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('work_hours_shift', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('additional_fee_charged', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('additional_fee_charged_unit', models.CharField(blank=True, default='$', max_length=10, null=True)),
                ('staff_rate_for_after_hours', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('staff_rate_for_after_hours_unit', models.CharField(blank=True, default='$', max_length=10, null=True)),
                ('weekend_fees_enabled', models.BooleanField(default=False)),
                ('weekend_fee_charged', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('weekend_fee_charged_unit', models.CharField(blank=True, default='$', max_length=10, null=True)),
                ('staff_rate_for_weekend', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('staff_rate_for_weekend_unit', models.CharField(blank=True, default='$', max_length=10, null=True)),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Service')),
            ],
        ),
    ]
